C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitellinfo(setupfunc)
      external setupfunc
      double precision ex1
      double precision ex2
      double precision earat
      double precision es2
      double precision egam
      common /ellinfo/ ex1,ex2,earat,es2,egam
      call setupfunc(ex1,ex2,earat,es2,egam)
      end

      subroutine f2pyinitellfirsttime(setupfunc)
      external setupfunc
      integer ifirst1
      integer ifirst2
      common /ellfirsttime/ ifirst1,ifirst2
      call setupfunc(ifirst1,ifirst2)
      end


