/* File: _fastellmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu May  7 17:55:48 2015
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_fastell_error;
static PyObject *_fastell_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(_fastell_error,errstring);\
    /*goto capi_fail;*/\
  } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _fastell_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = _fastell_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(ellipphi,ELLIPPHI)(double*,double*,double*,double*,double*,double*,double*);
extern void F_FUNC_US(ellipphi_array,ELLIPPHI_ARRAY)(double*,double*,double*,double*,double*,double*,double*,int*);
extern void F_FUNC(fastellmag,FASTELLMAG)(double*,double*,double*,double*,double*,double*,double*,double*);
extern void F_FUNC_US(fastellmag_array,FASTELLMAG_ARRAY)(double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*);
extern void F_FUNC(fastelldefl,FASTELLDEFL)(double*,double*,double*,double*,double*,double*,double*);
extern void F_FUNC_US(fastelldefl_array,FASTELLDEFL_ARRAY)(double*,double*,double*,double*,double*,double*,double*,double*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** ellipphi **********************************/
static char doc_f2py_rout__fastell_ellipphi[] = "\
ellipphi(x1,x2,q,gam,arat,s2,phi)\n\nWrapper for ``ellipphi``.\
\n\nParameters\n----------\n"
"x1 : input float\n"
"x2 : input float\n"
"q : input float\n"
"gam : input float\n"
"arat : input float\n"
"s2 : input float\n"
"phi : input float";
/* extern void F_FUNC(ellipphi,ELLIPPHI)(double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout__fastell_ellipphi(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double x1 = 0;
  PyObject *x1_capi = Py_None;
  double x2 = 0;
  PyObject *x2_capi = Py_None;
  double q = 0;
  PyObject *q_capi = Py_None;
  double gam = 0;
  PyObject *gam_capi = Py_None;
  double arat = 0;
  PyObject *arat_capi = Py_None;
  double s2 = 0;
  PyObject *s2_capi = Py_None;
  double phi = 0;
  PyObject *phi_capi = Py_None;
  static char *capi_kwlist[] = {"x1","x2","q","gam","arat","s2","phi",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:_fastell.ellipphi",\
    capi_kwlist,&x1_capi,&x2_capi,&q_capi,&gam_capi,&arat_capi,&s2_capi,&phi_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable phi */
    f2py_success = double_from_pyobj(&phi,phi_capi,"_fastell.ellipphi() 7th argument (phi) can't be converted to double");
  if (f2py_success) {
  /* Processing variable arat */
    f2py_success = double_from_pyobj(&arat,arat_capi,"_fastell.ellipphi() 5th argument (arat) can't be converted to double");
  if (f2py_success) {
  /* Processing variable s2 */
    f2py_success = double_from_pyobj(&s2,s2_capi,"_fastell.ellipphi() 6th argument (s2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable q */
    f2py_success = double_from_pyobj(&q,q_capi,"_fastell.ellipphi() 3rd argument (q) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gam */
    f2py_success = double_from_pyobj(&gam,gam_capi,"_fastell.ellipphi() 4th argument (gam) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x2 */
    f2py_success = double_from_pyobj(&x2,x2_capi,"_fastell.ellipphi() 2nd argument (x2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x1 */
    f2py_success = double_from_pyobj(&x1,x1_capi,"_fastell.ellipphi() 1st argument (x1) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&x1,&x2,&q,&gam,&arat,&s2,&phi);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of x1*/
  /* End of cleaning variable x1 */
  } /*if (f2py_success) of x2*/
  /* End of cleaning variable x2 */
  } /*if (f2py_success) of gam*/
  /* End of cleaning variable gam */
  } /*if (f2py_success) of q*/
  /* End of cleaning variable q */
  } /*if (f2py_success) of s2*/
  /* End of cleaning variable s2 */
  } /*if (f2py_success) of arat*/
  /* End of cleaning variable arat */
  } /*if (f2py_success) of phi*/
  /* End of cleaning variable phi */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of ellipphi ******************************/

/******************************* ellipphi_array *******************************/
static char doc_f2py_rout__fastell_ellipphi_array[] = "\
ellipphi_array(x1,x2,q,gam,arat,s2,phi,[n])\n\nWrapper for ``ellipphi_array``.\
\n\nParameters\n----------\n"
"x1 : input rank-1 array('d') with bounds (n)\n"
"x2 : input rank-1 array('d') with bounds (n)\n"
"q : input float\n"
"gam : input float\n"
"arat : input float\n"
"s2 : input float\n"
"phi : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(x1)";
/* extern void F_FUNC_US(ellipphi_array,ELLIPPHI_ARRAY)(double*,double*,double*,double*,double*,double*,double*,int*); */
static PyObject *f2py_rout__fastell_ellipphi_array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x1 = NULL;
  npy_intp x1_Dims[1] = {-1};
  const int x1_Rank = 1;
  PyArrayObject *capi_x1_tmp = NULL;
  int capi_x1_intent = 0;
  PyObject *x1_capi = Py_None;
  double *x2 = NULL;
  npy_intp x2_Dims[1] = {-1};
  const int x2_Rank = 1;
  PyArrayObject *capi_x2_tmp = NULL;
  int capi_x2_intent = 0;
  PyObject *x2_capi = Py_None;
  double q = 0;
  PyObject *q_capi = Py_None;
  double gam = 0;
  PyObject *gam_capi = Py_None;
  double arat = 0;
  PyObject *arat_capi = Py_None;
  double s2 = 0;
  PyObject *s2_capi = Py_None;
  double *phi = NULL;
  npy_intp phi_Dims[1] = {-1};
  const int phi_Rank = 1;
  PyArrayObject *capi_phi_tmp = NULL;
  int capi_phi_intent = 0;
  PyObject *phi_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  static char *capi_kwlist[] = {"x1","x2","q","gam","arat","s2","phi","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|O:_fastell.ellipphi_array",\
    capi_kwlist,&x1_capi,&x2_capi,&q_capi,&gam_capi,&arat_capi,&s2_capi,&phi_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable arat */
    f2py_success = double_from_pyobj(&arat,arat_capi,"_fastell.ellipphi_array() 5th argument (arat) can't be converted to double");
  if (f2py_success) {
  /* Processing variable s2 */
    f2py_success = double_from_pyobj(&s2,s2_capi,"_fastell.ellipphi_array() 6th argument (s2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable q */
    f2py_success = double_from_pyobj(&q,q_capi,"_fastell.ellipphi_array() 3rd argument (q) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gam */
    f2py_success = double_from_pyobj(&gam,gam_capi,"_fastell.ellipphi_array() 4th argument (gam) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x1 */
  ;
  capi_x1_intent |= F2PY_INTENT_IN;
  capi_x1_tmp = array_from_pyobj(NPY_DOUBLE,x1_Dims,x1_Rank,capi_x1_intent,x1_capi);
  if (capi_x1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 1st argument `x1' of _fastell.ellipphi_array to C/Fortran array" );
  } else {
    x1 = (double *)(capi_x1_tmp->data);

  /* Processing variable n */
  if (n_capi == Py_None) n = len(x1); else
    f2py_success = int_from_pyobj(&n,n_capi,"_fastell.ellipphi_array() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(x1)>=n,"len(x1)>=n","1st keyword n","ellipphi_array:n=%d",n) {
  /* Processing variable x2 */
  x2_Dims[0]=n;
  capi_x2_intent |= F2PY_INTENT_IN;
  capi_x2_tmp = array_from_pyobj(NPY_DOUBLE,x2_Dims,x2_Rank,capi_x2_intent,x2_capi);
  if (capi_x2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 2nd argument `x2' of _fastell.ellipphi_array to C/Fortran array" );
  } else {
    x2 = (double *)(capi_x2_tmp->data);

  /* Processing variable phi */
  phi_Dims[0]=n;
  capi_phi_intent |= F2PY_INTENT_IN;
  capi_phi_tmp = array_from_pyobj(NPY_DOUBLE,phi_Dims,phi_Rank,capi_phi_intent,phi_capi);
  if (capi_phi_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 7th argument `phi' of _fastell.ellipphi_array to C/Fortran array" );
  } else {
    phi = (double *)(capi_phi_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(x1,x2,&q,&gam,&arat,&s2,phi,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_phi_tmp!=phi_capi) {
    Py_XDECREF(capi_phi_tmp); }
  }  /*if (capi_phi_tmp == NULL) ... else of phi*/
  /* End of cleaning variable phi */
  if((PyObject *)capi_x2_tmp!=x2_capi) {
    Py_XDECREF(capi_x2_tmp); }
  }  /*if (capi_x2_tmp == NULL) ... else of x2*/
  /* End of cleaning variable x2 */
  } /*CHECKSCALAR(len(x1)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_x1_tmp!=x1_capi) {
    Py_XDECREF(capi_x1_tmp); }
  }  /*if (capi_x1_tmp == NULL) ... else of x1*/
  /* End of cleaning variable x1 */
  } /*if (f2py_success) of gam*/
  /* End of cleaning variable gam */
  } /*if (f2py_success) of q*/
  /* End of cleaning variable q */
  } /*if (f2py_success) of s2*/
  /* End of cleaning variable s2 */
  } /*if (f2py_success) of arat*/
  /* End of cleaning variable arat */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of ellipphi_array ***************************/

/********************************* fastellmag *********************************/
static char doc_f2py_rout__fastell_fastellmag[] = "\
fastellmag(x1in,x2in,q,gam,arat,s2,defl,magmx)\n\nWrapper for ``fastellmag``.\
\n\nParameters\n----------\n"
"x1in : input float\n"
"x2in : input float\n"
"q : input float\n"
"gam : input float\n"
"arat : input float\n"
"s2 : input float\n"
"defl : input rank-1 array('d') with bounds (2)\n"
"magmx : input rank-2 array('d') with bounds (2,2)";
/* extern void F_FUNC(fastellmag,FASTELLMAG)(double*,double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout__fastell_fastellmag(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double x1in = 0;
  PyObject *x1in_capi = Py_None;
  double x2in = 0;
  PyObject *x2in_capi = Py_None;
  double q = 0;
  PyObject *q_capi = Py_None;
  double gam = 0;
  PyObject *gam_capi = Py_None;
  double arat = 0;
  PyObject *arat_capi = Py_None;
  double s2 = 0;
  PyObject *s2_capi = Py_None;
  double *defl = NULL;
  npy_intp defl_Dims[1] = {-1};
  const int defl_Rank = 1;
  PyArrayObject *capi_defl_tmp = NULL;
  int capi_defl_intent = 0;
  PyObject *defl_capi = Py_None;
  double *magmx = NULL;
  npy_intp magmx_Dims[2] = {-1, -1};
  const int magmx_Rank = 2;
  PyArrayObject *capi_magmx_tmp = NULL;
  int capi_magmx_intent = 0;
  PyObject *magmx_capi = Py_None;
  static char *capi_kwlist[] = {"x1in","x2in","q","gam","arat","s2","defl","magmx",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:_fastell.fastellmag",\
    capi_kwlist,&x1in_capi,&x2in_capi,&q_capi,&gam_capi,&arat_capi,&s2_capi,&defl_capi,&magmx_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable arat */
    f2py_success = double_from_pyobj(&arat,arat_capi,"_fastell.fastellmag() 5th argument (arat) can't be converted to double");
  if (f2py_success) {
  /* Processing variable s2 */
    f2py_success = double_from_pyobj(&s2,s2_capi,"_fastell.fastellmag() 6th argument (s2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable magmx */
  magmx_Dims[0]=2,magmx_Dims[1]=2;
  capi_magmx_intent |= F2PY_INTENT_IN;
  capi_magmx_tmp = array_from_pyobj(NPY_DOUBLE,magmx_Dims,magmx_Rank,capi_magmx_intent,magmx_capi);
  if (capi_magmx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 8th argument `magmx' of _fastell.fastellmag to C/Fortran array" );
  } else {
    magmx = (double *)(capi_magmx_tmp->data);

  /* Processing variable x1in */
    f2py_success = double_from_pyobj(&x1in,x1in_capi,"_fastell.fastellmag() 1st argument (x1in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable q */
    f2py_success = double_from_pyobj(&q,q_capi,"_fastell.fastellmag() 3rd argument (q) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gam */
    f2py_success = double_from_pyobj(&gam,gam_capi,"_fastell.fastellmag() 4th argument (gam) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x2in */
    f2py_success = double_from_pyobj(&x2in,x2in_capi,"_fastell.fastellmag() 2nd argument (x2in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable defl */
  defl_Dims[0]=2;
  capi_defl_intent |= F2PY_INTENT_IN;
  capi_defl_tmp = array_from_pyobj(NPY_DOUBLE,defl_Dims,defl_Rank,capi_defl_intent,defl_capi);
  if (capi_defl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 7th argument `defl' of _fastell.fastellmag to C/Fortran array" );
  } else {
    defl = (double *)(capi_defl_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&x1in,&x2in,&q,&gam,&arat,&s2,defl,magmx);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_defl_tmp!=defl_capi) {
    Py_XDECREF(capi_defl_tmp); }
  }  /*if (capi_defl_tmp == NULL) ... else of defl*/
  /* End of cleaning variable defl */
  } /*if (f2py_success) of x2in*/
  /* End of cleaning variable x2in */
  } /*if (f2py_success) of gam*/
  /* End of cleaning variable gam */
  } /*if (f2py_success) of q*/
  /* End of cleaning variable q */
  } /*if (f2py_success) of x1in*/
  /* End of cleaning variable x1in */
  if((PyObject *)capi_magmx_tmp!=magmx_capi) {
    Py_XDECREF(capi_magmx_tmp); }
  }  /*if (capi_magmx_tmp == NULL) ... else of magmx*/
  /* End of cleaning variable magmx */
  } /*if (f2py_success) of s2*/
  /* End of cleaning variable s2 */
  } /*if (f2py_success) of arat*/
  /* End of cleaning variable arat */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of fastellmag *****************************/

/****************************** fastellmag_array ******************************/
static char doc_f2py_rout__fastell_fastellmag_array[] = "\
fastellmag_array(x1in,x2in,q,gam,arat,s2,defl1,defl2,magmx_xx,magmx_xy,magmx_yy,[n])\n\nWrapper for ``fastellmag_array``.\
\n\nParameters\n----------\n"
"x1in : input rank-1 array('d') with bounds (n)\n"
"x2in : input rank-1 array('d') with bounds (n)\n"
"q : input float\n"
"gam : input float\n"
"arat : input float\n"
"s2 : input float\n"
"defl1 : input rank-1 array('d') with bounds (n)\n"
"defl2 : input rank-1 array('d') with bounds (n)\n"
"magmx_xx : input rank-1 array('d') with bounds (n)\n"
"magmx_xy : input rank-1 array('d') with bounds (n)\n"
"magmx_yy : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(x1in)";
/* extern void F_FUNC_US(fastellmag_array,FASTELLMAG_ARRAY)(double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*); */
static PyObject *f2py_rout__fastell_fastellmag_array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x1in = NULL;
  npy_intp x1in_Dims[1] = {-1};
  const int x1in_Rank = 1;
  PyArrayObject *capi_x1in_tmp = NULL;
  int capi_x1in_intent = 0;
  PyObject *x1in_capi = Py_None;
  double *x2in = NULL;
  npy_intp x2in_Dims[1] = {-1};
  const int x2in_Rank = 1;
  PyArrayObject *capi_x2in_tmp = NULL;
  int capi_x2in_intent = 0;
  PyObject *x2in_capi = Py_None;
  double q = 0;
  PyObject *q_capi = Py_None;
  double gam = 0;
  PyObject *gam_capi = Py_None;
  double arat = 0;
  PyObject *arat_capi = Py_None;
  double s2 = 0;
  PyObject *s2_capi = Py_None;
  double *defl1 = NULL;
  npy_intp defl1_Dims[1] = {-1};
  const int defl1_Rank = 1;
  PyArrayObject *capi_defl1_tmp = NULL;
  int capi_defl1_intent = 0;
  PyObject *defl1_capi = Py_None;
  double *defl2 = NULL;
  npy_intp defl2_Dims[1] = {-1};
  const int defl2_Rank = 1;
  PyArrayObject *capi_defl2_tmp = NULL;
  int capi_defl2_intent = 0;
  PyObject *defl2_capi = Py_None;
  double *magmx_xx = NULL;
  npy_intp magmx_xx_Dims[1] = {-1};
  const int magmx_xx_Rank = 1;
  PyArrayObject *capi_magmx_xx_tmp = NULL;
  int capi_magmx_xx_intent = 0;
  PyObject *magmx_xx_capi = Py_None;
  double *magmx_xy = NULL;
  npy_intp magmx_xy_Dims[1] = {-1};
  const int magmx_xy_Rank = 1;
  PyArrayObject *capi_magmx_xy_tmp = NULL;
  int capi_magmx_xy_intent = 0;
  PyObject *magmx_xy_capi = Py_None;
  double *magmx_yy = NULL;
  npy_intp magmx_yy_Dims[1] = {-1};
  const int magmx_yy_Rank = 1;
  PyArrayObject *capi_magmx_yy_tmp = NULL;
  int capi_magmx_yy_intent = 0;
  PyObject *magmx_yy_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  static char *capi_kwlist[] = {"x1in","x2in","q","gam","arat","s2","defl1","defl2","magmx_xx","magmx_xy","magmx_yy","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|O:_fastell.fastellmag_array",\
    capi_kwlist,&x1in_capi,&x2in_capi,&q_capi,&gam_capi,&arat_capi,&s2_capi,&defl1_capi,&defl2_capi,&magmx_xx_capi,&magmx_xy_capi,&magmx_yy_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable arat */
    f2py_success = double_from_pyobj(&arat,arat_capi,"_fastell.fastellmag_array() 5th argument (arat) can't be converted to double");
  if (f2py_success) {
  /* Processing variable s2 */
    f2py_success = double_from_pyobj(&s2,s2_capi,"_fastell.fastellmag_array() 6th argument (s2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x1in */
  ;
  capi_x1in_intent |= F2PY_INTENT_IN;
  capi_x1in_tmp = array_from_pyobj(NPY_DOUBLE,x1in_Dims,x1in_Rank,capi_x1in_intent,x1in_capi);
  if (capi_x1in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 1st argument `x1in' of _fastell.fastellmag_array to C/Fortran array" );
  } else {
    x1in = (double *)(capi_x1in_tmp->data);

  /* Processing variable q */
    f2py_success = double_from_pyobj(&q,q_capi,"_fastell.fastellmag_array() 3rd argument (q) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gam */
    f2py_success = double_from_pyobj(&gam,gam_capi,"_fastell.fastellmag_array() 4th argument (gam) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(x1in); else
    f2py_success = int_from_pyobj(&n,n_capi,"_fastell.fastellmag_array() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(x1in)>=n,"len(x1in)>=n","1st keyword n","fastellmag_array:n=%d",n) {
  /* Processing variable x2in */
  x2in_Dims[0]=n;
  capi_x2in_intent |= F2PY_INTENT_IN;
  capi_x2in_tmp = array_from_pyobj(NPY_DOUBLE,x2in_Dims,x2in_Rank,capi_x2in_intent,x2in_capi);
  if (capi_x2in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 2nd argument `x2in' of _fastell.fastellmag_array to C/Fortran array" );
  } else {
    x2in = (double *)(capi_x2in_tmp->data);

  /* Processing variable defl1 */
  defl1_Dims[0]=n;
  capi_defl1_intent |= F2PY_INTENT_IN;
  capi_defl1_tmp = array_from_pyobj(NPY_DOUBLE,defl1_Dims,defl1_Rank,capi_defl1_intent,defl1_capi);
  if (capi_defl1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 7th argument `defl1' of _fastell.fastellmag_array to C/Fortran array" );
  } else {
    defl1 = (double *)(capi_defl1_tmp->data);

  /* Processing variable magmx_yy */
  magmx_yy_Dims[0]=n;
  capi_magmx_yy_intent |= F2PY_INTENT_IN;
  capi_magmx_yy_tmp = array_from_pyobj(NPY_DOUBLE,magmx_yy_Dims,magmx_yy_Rank,capi_magmx_yy_intent,magmx_yy_capi);
  if (capi_magmx_yy_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 11st argument `magmx_yy' of _fastell.fastellmag_array to C/Fortran array" );
  } else {
    magmx_yy = (double *)(capi_magmx_yy_tmp->data);

  /* Processing variable magmx_xy */
  magmx_xy_Dims[0]=n;
  capi_magmx_xy_intent |= F2PY_INTENT_IN;
  capi_magmx_xy_tmp = array_from_pyobj(NPY_DOUBLE,magmx_xy_Dims,magmx_xy_Rank,capi_magmx_xy_intent,magmx_xy_capi);
  if (capi_magmx_xy_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 10th argument `magmx_xy' of _fastell.fastellmag_array to C/Fortran array" );
  } else {
    magmx_xy = (double *)(capi_magmx_xy_tmp->data);

  /* Processing variable magmx_xx */
  magmx_xx_Dims[0]=n;
  capi_magmx_xx_intent |= F2PY_INTENT_IN;
  capi_magmx_xx_tmp = array_from_pyobj(NPY_DOUBLE,magmx_xx_Dims,magmx_xx_Rank,capi_magmx_xx_intent,magmx_xx_capi);
  if (capi_magmx_xx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 9th argument `magmx_xx' of _fastell.fastellmag_array to C/Fortran array" );
  } else {
    magmx_xx = (double *)(capi_magmx_xx_tmp->data);

  /* Processing variable defl2 */
  defl2_Dims[0]=n;
  capi_defl2_intent |= F2PY_INTENT_IN;
  capi_defl2_tmp = array_from_pyobj(NPY_DOUBLE,defl2_Dims,defl2_Rank,capi_defl2_intent,defl2_capi);
  if (capi_defl2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 8th argument `defl2' of _fastell.fastellmag_array to C/Fortran array" );
  } else {
    defl2 = (double *)(capi_defl2_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(x1in,x2in,&q,&gam,&arat,&s2,defl1,defl2,magmx_xx,magmx_xy,magmx_yy,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_defl2_tmp!=defl2_capi) {
    Py_XDECREF(capi_defl2_tmp); }
  }  /*if (capi_defl2_tmp == NULL) ... else of defl2*/
  /* End of cleaning variable defl2 */
  if((PyObject *)capi_magmx_xx_tmp!=magmx_xx_capi) {
    Py_XDECREF(capi_magmx_xx_tmp); }
  }  /*if (capi_magmx_xx_tmp == NULL) ... else of magmx_xx*/
  /* End of cleaning variable magmx_xx */
  if((PyObject *)capi_magmx_xy_tmp!=magmx_xy_capi) {
    Py_XDECREF(capi_magmx_xy_tmp); }
  }  /*if (capi_magmx_xy_tmp == NULL) ... else of magmx_xy*/
  /* End of cleaning variable magmx_xy */
  if((PyObject *)capi_magmx_yy_tmp!=magmx_yy_capi) {
    Py_XDECREF(capi_magmx_yy_tmp); }
  }  /*if (capi_magmx_yy_tmp == NULL) ... else of magmx_yy*/
  /* End of cleaning variable magmx_yy */
  if((PyObject *)capi_defl1_tmp!=defl1_capi) {
    Py_XDECREF(capi_defl1_tmp); }
  }  /*if (capi_defl1_tmp == NULL) ... else of defl1*/
  /* End of cleaning variable defl1 */
  if((PyObject *)capi_x2in_tmp!=x2in_capi) {
    Py_XDECREF(capi_x2in_tmp); }
  }  /*if (capi_x2in_tmp == NULL) ... else of x2in*/
  /* End of cleaning variable x2in */
  } /*CHECKSCALAR(len(x1in)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of gam*/
  /* End of cleaning variable gam */
  } /*if (f2py_success) of q*/
  /* End of cleaning variable q */
  if((PyObject *)capi_x1in_tmp!=x1in_capi) {
    Py_XDECREF(capi_x1in_tmp); }
  }  /*if (capi_x1in_tmp == NULL) ... else of x1in*/
  /* End of cleaning variable x1in */
  } /*if (f2py_success) of s2*/
  /* End of cleaning variable s2 */
  } /*if (f2py_success) of arat*/
  /* End of cleaning variable arat */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of fastellmag_array **************************/

/******************************** fastelldefl ********************************/
static char doc_f2py_rout__fastell_fastelldefl[] = "\
fastelldefl(x1in,x2in,q,gam,arat,s2,defl)\n\nWrapper for ``fastelldefl``.\
\n\nParameters\n----------\n"
"x1in : input float\n"
"x2in : input float\n"
"q : input float\n"
"gam : input float\n"
"arat : input float\n"
"s2 : input float\n"
"defl : input rank-1 array('d') with bounds (2)";
/* extern void F_FUNC(fastelldefl,FASTELLDEFL)(double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout__fastell_fastelldefl(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double x1in = 0;
  PyObject *x1in_capi = Py_None;
  double x2in = 0;
  PyObject *x2in_capi = Py_None;
  double q = 0;
  PyObject *q_capi = Py_None;
  double gam = 0;
  PyObject *gam_capi = Py_None;
  double arat = 0;
  PyObject *arat_capi = Py_None;
  double s2 = 0;
  PyObject *s2_capi = Py_None;
  double *defl = NULL;
  npy_intp defl_Dims[1] = {-1};
  const int defl_Rank = 1;
  PyArrayObject *capi_defl_tmp = NULL;
  int capi_defl_intent = 0;
  PyObject *defl_capi = Py_None;
  static char *capi_kwlist[] = {"x1in","x2in","q","gam","arat","s2","defl",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:_fastell.fastelldefl",\
    capi_kwlist,&x1in_capi,&x2in_capi,&q_capi,&gam_capi,&arat_capi,&s2_capi,&defl_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable arat */
    f2py_success = double_from_pyobj(&arat,arat_capi,"_fastell.fastelldefl() 5th argument (arat) can't be converted to double");
  if (f2py_success) {
  /* Processing variable s2 */
    f2py_success = double_from_pyobj(&s2,s2_capi,"_fastell.fastelldefl() 6th argument (s2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x1in */
    f2py_success = double_from_pyobj(&x1in,x1in_capi,"_fastell.fastelldefl() 1st argument (x1in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable q */
    f2py_success = double_from_pyobj(&q,q_capi,"_fastell.fastelldefl() 3rd argument (q) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gam */
    f2py_success = double_from_pyobj(&gam,gam_capi,"_fastell.fastelldefl() 4th argument (gam) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x2in */
    f2py_success = double_from_pyobj(&x2in,x2in_capi,"_fastell.fastelldefl() 2nd argument (x2in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable defl */
  defl_Dims[0]=2;
  capi_defl_intent |= F2PY_INTENT_IN;
  capi_defl_tmp = array_from_pyobj(NPY_DOUBLE,defl_Dims,defl_Rank,capi_defl_intent,defl_capi);
  if (capi_defl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 7th argument `defl' of _fastell.fastelldefl to C/Fortran array" );
  } else {
    defl = (double *)(capi_defl_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&x1in,&x2in,&q,&gam,&arat,&s2,defl);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_defl_tmp!=defl_capi) {
    Py_XDECREF(capi_defl_tmp); }
  }  /*if (capi_defl_tmp == NULL) ... else of defl*/
  /* End of cleaning variable defl */
  } /*if (f2py_success) of x2in*/
  /* End of cleaning variable x2in */
  } /*if (f2py_success) of gam*/
  /* End of cleaning variable gam */
  } /*if (f2py_success) of q*/
  /* End of cleaning variable q */
  } /*if (f2py_success) of x1in*/
  /* End of cleaning variable x1in */
  } /*if (f2py_success) of s2*/
  /* End of cleaning variable s2 */
  } /*if (f2py_success) of arat*/
  /* End of cleaning variable arat */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of fastelldefl *****************************/

/***************************** fastelldefl_array *****************************/
static char doc_f2py_rout__fastell_fastelldefl_array[] = "\
fastelldefl_array(x1in,x2in,q,gam,arat,s2,defl1,defl2,[n])\n\nWrapper for ``fastelldefl_array``.\
\n\nParameters\n----------\n"
"x1in : input rank-1 array('d') with bounds (n)\n"
"x2in : input rank-1 array('d') with bounds (n)\n"
"q : input float\n"
"gam : input float\n"
"arat : input float\n"
"s2 : input float\n"
"defl1 : input rank-1 array('d') with bounds (n)\n"
"defl2 : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(x1in)";
/* extern void F_FUNC_US(fastelldefl_array,FASTELLDEFL_ARRAY)(double*,double*,double*,double*,double*,double*,double*,double*,int*); */
static PyObject *f2py_rout__fastell_fastelldefl_array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x1in = NULL;
  npy_intp x1in_Dims[1] = {-1};
  const int x1in_Rank = 1;
  PyArrayObject *capi_x1in_tmp = NULL;
  int capi_x1in_intent = 0;
  PyObject *x1in_capi = Py_None;
  double *x2in = NULL;
  npy_intp x2in_Dims[1] = {-1};
  const int x2in_Rank = 1;
  PyArrayObject *capi_x2in_tmp = NULL;
  int capi_x2in_intent = 0;
  PyObject *x2in_capi = Py_None;
  double q = 0;
  PyObject *q_capi = Py_None;
  double gam = 0;
  PyObject *gam_capi = Py_None;
  double arat = 0;
  PyObject *arat_capi = Py_None;
  double s2 = 0;
  PyObject *s2_capi = Py_None;
  double *defl1 = NULL;
  npy_intp defl1_Dims[1] = {-1};
  const int defl1_Rank = 1;
  PyArrayObject *capi_defl1_tmp = NULL;
  int capi_defl1_intent = 0;
  PyObject *defl1_capi = Py_None;
  double *defl2 = NULL;
  npy_intp defl2_Dims[1] = {-1};
  const int defl2_Rank = 1;
  PyArrayObject *capi_defl2_tmp = NULL;
  int capi_defl2_intent = 0;
  PyObject *defl2_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  static char *capi_kwlist[] = {"x1in","x2in","q","gam","arat","s2","defl1","defl2","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|O:_fastell.fastelldefl_array",\
    capi_kwlist,&x1in_capi,&x2in_capi,&q_capi,&gam_capi,&arat_capi,&s2_capi,&defl1_capi,&defl2_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable arat */
    f2py_success = double_from_pyobj(&arat,arat_capi,"_fastell.fastelldefl_array() 5th argument (arat) can't be converted to double");
  if (f2py_success) {
  /* Processing variable s2 */
    f2py_success = double_from_pyobj(&s2,s2_capi,"_fastell.fastelldefl_array() 6th argument (s2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x1in */
  ;
  capi_x1in_intent |= F2PY_INTENT_IN;
  capi_x1in_tmp = array_from_pyobj(NPY_DOUBLE,x1in_Dims,x1in_Rank,capi_x1in_intent,x1in_capi);
  if (capi_x1in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 1st argument `x1in' of _fastell.fastelldefl_array to C/Fortran array" );
  } else {
    x1in = (double *)(capi_x1in_tmp->data);

  /* Processing variable q */
    f2py_success = double_from_pyobj(&q,q_capi,"_fastell.fastelldefl_array() 3rd argument (q) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gam */
    f2py_success = double_from_pyobj(&gam,gam_capi,"_fastell.fastelldefl_array() 4th argument (gam) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(x1in); else
    f2py_success = int_from_pyobj(&n,n_capi,"_fastell.fastelldefl_array() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(x1in)>=n,"len(x1in)>=n","1st keyword n","fastelldefl_array:n=%d",n) {
  /* Processing variable x2in */
  x2in_Dims[0]=n;
  capi_x2in_intent |= F2PY_INTENT_IN;
  capi_x2in_tmp = array_from_pyobj(NPY_DOUBLE,x2in_Dims,x2in_Rank,capi_x2in_intent,x2in_capi);
  if (capi_x2in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 2nd argument `x2in' of _fastell.fastelldefl_array to C/Fortran array" );
  } else {
    x2in = (double *)(capi_x2in_tmp->data);

  /* Processing variable defl1 */
  defl1_Dims[0]=n;
  capi_defl1_intent |= F2PY_INTENT_IN;
  capi_defl1_tmp = array_from_pyobj(NPY_DOUBLE,defl1_Dims,defl1_Rank,capi_defl1_intent,defl1_capi);
  if (capi_defl1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 7th argument `defl1' of _fastell.fastelldefl_array to C/Fortran array" );
  } else {
    defl1 = (double *)(capi_defl1_tmp->data);

  /* Processing variable defl2 */
  defl2_Dims[0]=n;
  capi_defl2_intent |= F2PY_INTENT_IN;
  capi_defl2_tmp = array_from_pyobj(NPY_DOUBLE,defl2_Dims,defl2_Rank,capi_defl2_intent,defl2_capi);
  if (capi_defl2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(_fastell_error,"failed in converting 8th argument `defl2' of _fastell.fastelldefl_array to C/Fortran array" );
  } else {
    defl2 = (double *)(capi_defl2_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(x1in,x2in,&q,&gam,&arat,&s2,defl1,defl2,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_defl2_tmp!=defl2_capi) {
    Py_XDECREF(capi_defl2_tmp); }
  }  /*if (capi_defl2_tmp == NULL) ... else of defl2*/
  /* End of cleaning variable defl2 */
  if((PyObject *)capi_defl1_tmp!=defl1_capi) {
    Py_XDECREF(capi_defl1_tmp); }
  }  /*if (capi_defl1_tmp == NULL) ... else of defl1*/
  /* End of cleaning variable defl1 */
  if((PyObject *)capi_x2in_tmp!=x2in_capi) {
    Py_XDECREF(capi_x2in_tmp); }
  }  /*if (capi_x2in_tmp == NULL) ... else of x2in*/
  /* End of cleaning variable x2in */
  } /*CHECKSCALAR(len(x1in)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of gam*/
  /* End of cleaning variable gam */
  } /*if (f2py_success) of q*/
  /* End of cleaning variable q */
  if((PyObject *)capi_x1in_tmp!=x1in_capi) {
    Py_XDECREF(capi_x1in_tmp); }
  }  /*if (capi_x1in_tmp == NULL) ... else of x1in*/
  /* End of cleaning variable x1in */
  } /*if (f2py_success) of s2*/
  /* End of cleaning variable s2 */
  } /*if (f2py_success) of arat*/
  /* End of cleaning variable arat */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of fastelldefl_array **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_ellinfo_def[] = {
  {"ex1",0,{{-1}},NPY_DOUBLE},
  {"ex2",0,{{-1}},NPY_DOUBLE},
  {"earat",0,{{-1}},NPY_DOUBLE},
  {"es2",0,{{-1}},NPY_DOUBLE},
  {"egam",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_ellinfo(char *ex1,char *ex2,char *earat,char *es2,char *egam) {
  int i_f2py=0;
  f2py_ellinfo_def[i_f2py++].data = ex1;
  f2py_ellinfo_def[i_f2py++].data = ex2;
  f2py_ellinfo_def[i_f2py++].data = earat;
  f2py_ellinfo_def[i_f2py++].data = es2;
  f2py_ellinfo_def[i_f2py++].data = egam;
}
extern void F_FUNC(f2pyinitellinfo,F2PYINITELLINFO)(void(*)(char*,char*,char*,char*,char*));
static void f2py_init_ellinfo(void) {
  F_FUNC(f2pyinitellinfo,F2PYINITELLINFO)(f2py_setup_ellinfo);
}

static FortranDataDef f2py_ellfirsttime_def[] = {
  {"ifirst1",0,{{-1}},NPY_INT},
  {"ifirst2",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_ellfirsttime(char *ifirst1,char *ifirst2) {
  int i_f2py=0;
  f2py_ellfirsttime_def[i_f2py++].data = ifirst1;
  f2py_ellfirsttime_def[i_f2py++].data = ifirst2;
}
extern void F_FUNC(f2pyinitellfirsttime,F2PYINITELLFIRSTTIME)(void(*)(char*,char*));
static void f2py_init_ellfirsttime(void) {
  F_FUNC(f2pyinitellfirsttime,F2PYINITELLFIRSTTIME)(f2py_setup_ellfirsttime);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"ellipphi",-1,{{-1}},0,(char *)F_FUNC(ellipphi,ELLIPPHI),(f2py_init_func)f2py_rout__fastell_ellipphi,doc_f2py_rout__fastell_ellipphi},
  {"ellipphi_array",-1,{{-1}},0,(char *)F_FUNC_US(ellipphi_array,ELLIPPHI_ARRAY),(f2py_init_func)f2py_rout__fastell_ellipphi_array,doc_f2py_rout__fastell_ellipphi_array},
  {"fastellmag",-1,{{-1}},0,(char *)F_FUNC(fastellmag,FASTELLMAG),(f2py_init_func)f2py_rout__fastell_fastellmag,doc_f2py_rout__fastell_fastellmag},
  {"fastellmag_array",-1,{{-1}},0,(char *)F_FUNC_US(fastellmag_array,FASTELLMAG_ARRAY),(f2py_init_func)f2py_rout__fastell_fastellmag_array,doc_f2py_rout__fastell_fastellmag_array},
  {"fastelldefl",-1,{{-1}},0,(char *)F_FUNC(fastelldefl,FASTELLDEFL),(f2py_init_func)f2py_rout__fastell_fastelldefl,doc_f2py_rout__fastell_fastelldefl},
  {"fastelldefl_array",-1,{{-1}},0,(char *)F_FUNC_US(fastelldefl_array,FASTELLDEFL_ARRAY),(f2py_init_func)f2py_rout__fastell_fastelldefl_array,doc_f2py_rout__fastell_fastelldefl_array},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_fastell",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit__fastell(void) {
#else
#define RETVAL
PyMODINIT_FUNC init_fastell(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = _fastell_module = PyModule_Create(&moduledef);
#else
  m = _fastell_module = Py_InitModule("_fastell", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _fastell (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module '_fastell' is auto-generated with f2py (version:2).\nFunctions:\n"
"  ellipphi(x1,x2,q,gam,arat,s2,phi)\n"
"  ellipphi_array(x1,x2,q,gam,arat,s2,phi,n=len(x1))\n"
"  fastellmag(x1in,x2in,q,gam,arat,s2,defl,magmx)\n"
"  fastellmag_array(x1in,x2in,q,gam,arat,s2,defl1,defl2,magmx_xx,magmx_xy,magmx_yy,n=len(x1in))\n"
"  fastelldefl(x1in,x2in,q,gam,arat,s2,defl)\n"
"  fastelldefl_array(x1in,x2in,q,gam,arat,s2,defl1,defl2,n=len(x1in))\n"
"COMMON blocks:\n""  /ellinfo/ ex1,ex2,earat,es2,egam\n""  /ellfirsttime/ ifirst1,ifirst2\n"".");
  PyDict_SetItemString(d, "__doc__", s);
  _fastell_error = PyErr_NewException ("_fastell.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));






/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  F2PyDict_SetItemString(d, "ellinfo", PyFortranObject_New(f2py_ellinfo_def,f2py_init_ellinfo));
  F2PyDict_SetItemString(d, "ellfirsttime", PyFortranObject_New(f2py_ellfirsttime_def,f2py_init_ellfirsttime));
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_fastell");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
